name: Add PR to Project Board

on:
  pull_request:
    types: [opened]

jobs:
  add-to-project:
    name: Add PR to Project Board
    runs-on: ubuntu-latest

    steps:
      - name: Add PR to project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/users/QuingKhaos/projects/3
          github-token: ${{ secrets.ADD_TO_PROJECT_TOKEN }}
